Fine view #31
BaldClub/data-view pull request #33
Opened 2023-03-19 10:59 UTC by bzpen

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2023-03-19 13:26 UTC, wangrunlin requested changes

2023-03-19 13:26 UTC, wangrunlin commented on src/views/fram-work/components/right/right-one.vue
> +export default {
```suggestion
import { dateYears } from "../../data";

export default {
```

2023-03-19 13:26 UTC, wangrunlin commented on src/views/index/components/right/right-three.vue
> +import dataList from '../../data/policy-data.json'
```suggestion
import dataList from '../../data/policy-data.json'

```

import 之间增加空行，下同

2023-03-19 13:26 UTC, wangrunlin commented on src/views/monitor/components/left/left-two.vue
> +              <td>2023-01-11</td>
是否需要 item.time ?

2023-03-19 13:26 UTC, wangrunlin commented on src/views/monitor/components/right/right-one.vue
>      </div>
使用循环之后，之前用来占位的代码是否还需要？

2023-03-19 13:26 UTC, wangrunlin commented on src/views/production/components/conter/conter-one.vue
> -    <div class="video" v-for="item in 4">
尽量修改数据而不是频繁变更代码

2023-03-25 04:11 UTC, bzpen commented on src/views/production/components/conter/conter-one.vue
> -    <div class="video" v-for="item in 4">
该分支用来满足界面截屏需求，不合并可能更合理些

2023-04-04 01:11 UTC, bzpen commented on src/views/environmental/components/left/left-one.vue
> +import { weatherData } from '../../data'
建议使用weatherSiteData，我感觉有点和天气相冲突

2023-04-04 01:11 UTC, bzpen commented on src/views/monitor/components/right/right-one.vue
>      </div>
不需要

2023-04-04 01:11 UTC, bzpen commented on src/views/monitor/components/left/left-two.vue
> +              <td>2023-01-11</td>
需要的

2023-04-04 01:12 UTC, bzpen commented on src/views/index/components/right/right-three.vue
> +import dataList from '../../data/policy-data.json'
欧克

2023-04-06 17:16 UTC, wangrunlin approved these changes

2023-04-06 17:17 UTC, merged